package com.topic;

import com.BaseTest;

public class PmpMock1 extends BaseTest {
	public PmpMock1(String result) {
		super("CDBBBBABABCABBABADABCADAABCDCBABCDBBABABBAABBBADCCBDBAACDACDCCDDBBABBAAABABACACAACAACBDCADCACDCABCBBDCADAACABAADCCDACCCCBDCCBCDBACBBCBBACBABDDBACCDDDBBABAACCAACBDCCCBCBACADBDDBADCADABDCBABABCBBCCACCDC");
	}

	public static void main(String[] args) {
		PmpMock1 pm1 = new PmpMock1(null);
		// 2018-1-31
		String re2 = "CDBBBBABABCABBABADABCADAABCDCCABCDABABACBABDBCBDCCBCBAACDACBACDDBBAAAABABCCACDCAACAACBDCADCACDCABCBBDCABBACABCADCCDCACCABDACBCDBACABCBBACDDBDBBACCDDABCAAAACCAACBDCCCBDBACADBDDBADDADABACBABABBABBBBDCDC";
		pm1.test(re2);
	}

}
