package com.topic.auraPmpMock;

import com.base.BaseTest;

/**
 * 光环HD1801班3模
 * 
 * @author JianDe
 */
public class PmpMock3 extends BaseTest {
    public PmpMock3(String result) {
        super("CDABBCDDABCCDBABDDDDDCBABDCCBABBBDBCDCABADCBBABDCADCCCABCADCDDDDBBCBDCBDADBADCBBABDCDDBCABDBCBBBAABA"
                + "CCCBDBDAAACADABDABADABBDDCCDDDCCBBDCAAADCABCCBCDACCCDBBBBACADAAAACAAABCCCCABCCABDADCCBBDAACDBADCACCA");
    }

    public static void main(String[] args) {
        PmpMock3 pm1 = new PmpMock3(null);
        System.out.println("2018-03-10");
        String re1 = "CDCBBCDDCACCDBABDDADBCBAAACCBABDADBCDCABADCDBBBDCDBCDCCDCADCDDCCCBABBCDCADBCBCACABACDDBCBCDBDBBAAABA "
                + "CDACABBADACBDBCDABADABBDDCBDCCCCAADBAADDCABCCBCDDCACDBBBBAAADABBDCBABBACACDBACCDDABCCBBCCACDBADCDBAA";
        pm1.test(re1);
    }

}
