package com.topic.auraPmpMock;

import com.base.BaseTest;

/**
 * 光环HD1801班1模
 * 
 * @author JianDe
 */
public class PmpMock1 extends BaseTest {
    public PmpMock1(String result) {
        super("CDBBBBABABCABBABADABCADAABCDCBABCDBBABABBAABBBADCCBDBAACDACDCCDDBBABBAAABABACACAACAACBDCADCACDCABCBB"
                + "DCADAACABAADCCDACCCCBDCCBCDBACBBCBBACBABDDBACCDDDBBABAACCAACBDCCCBCBACADBDDBADCADABDCBABABCBBCCACCDC");
    }

    public static void main(String[] args) {
        PmpMock1 pm1 = new PmpMock1(null);
        System.out.println("2018-01-28");
        String re1 = "DCBBDBDCBD CAADAAADAB CDDAADCDCB AAACBBAABC CCBBBCBDCC BDBABCCBBC CBDDDBAACD CABCCDCDAA ACACBCACAD CACDCDCBAB"
                + " DBABCACADC DDBCDCDCCA BDACDBDAAC ABCBBAADDD CBBDCCDCBB CDAAACCDAD BDCACBDBBD ADBBDBADAA DAAABDBACD DAABBBACDB";
        pm1.test(re1);
        System.out.println("2018-01-31");
        String re2 = "CDBBBBABABCABBABADAB CADAABCDCCABCDABABAC BABDBCBDCCBCBAACDACB ACDDBBAAAABABCCACDCA ACAACBDCADCACDCABCBB"
                + " DCABBACABCADCCDCACCA BDACBCDBACABCBBACDDB DBBACCDDABCAAAACCAAC BDCCCBDBACADBDDBADDA DABACBABABBABBBBDCDC";
        pm1.test(re2);
        System.out.println("2018-02-28");
        String re3 = "DDBBBBABDB CABBABCDAB CDDAADCDCA AACDDBABAC BABCBCBDCC BDBAACDBCC CCDDBBAACB CABCCACDCA ACACCBDCAD CACDCABCBB"
                + " CBABCACABC ADBCDCCCCA BDACBBDBAC ABCBBACBDD DBBACCDDBB CAAAACCAAC BDCCCBDBAC ADBDDBADCA DAAACBAACD CABBBBDCDC";
        pm1.test(re3);
    }

}
